src/Entity/Excuse.php
<?php

namespace App\Entity;

use App\Repository\ExcuseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExcuseRepository::class)]
#[ORM\Table(name: "excuse")]
class Excuse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(name: "http_code")]
    private ?int $http_code = null;

    #[ORM\Column(length: 255, name: "message")]
    private ?string $message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHttpCode(): ?int
    {
        return $this->http_code;
    }

    public function setHttpCode(int $http_code): self
    {
        $this->http_code = $http_code;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

src/Form/ExcuseType.php
<?php

namespace App\Form;

use App\Entity\Excuse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExcuseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('http_code', IntegerType::class)
            ->add('message', TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Excuse::class,
        ]);
    }
}

src/Controller/ExcuseController.php
<?php

namespace App\Controller;

use App\Repository\ExcuseRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Excuse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ExcuseType;

class ExcuseController extends AbstractController
{
    private $previouslyPicked = "";

    #[Route("/", name: "app_index")]
    public function index(ExcuseRepository $repo): Response
    {
        $excuses = $repo->findAll();

        return $this->render('base.html.twig', [
            "excuses" => $excuses
        ]);
    }

    #[Route('/lost', name: "app_lost")]
    public function lost(): Response
    {
        return $this->render("lost/lost.html.twig");
    }

    #[Route("/random", name: "app_random")]
    public function random(ExcuseRepository $repo): Response
    {
        $excusesList = $repo->findAll();
        do {
            $randomNumber = rand(0, count($excusesList) - 1);
        } while ($randomNumber == $this->previouslyPicked);
        $this->previouslyPicked = $randomNumber;
        $excuses = array($excusesList[$randomNumber]);

        return $this->render('excuse/index.html.twig', [
            "excuses" => $excuses
        ]);
    }

    #[Route("/add", name: "app_add")]
    public function add(EntityManagerInterface $entityManager, Request $request, ExcuseRepository $repo): Response
    {
        $excuse = new Excuse();
        $form = $this->createForm(ExcuseType::class, $excuse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($repo->findOneBy(["http_code" => $form->get('http_code')->getData()])) {
                return $this->render('excuseForm/index.html.twig', [
                    'form' => $form->createView(),
                    "error" => "Invalid Code"
                ]);
            } else {
                $excuse->setHttpCode($form->get('http_code')->getData());
                $excuse->setMessage($form->get('message')->getData());
                $entityManager->persist($excuse);
                $entityManager->flush();

                return new Response("Successfully added");
            }
        }

        return $this->render('excuseForm/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route("/{http_code}", name: "app_message")]
    public function message($http_code, ExcuseRepository $repo): Response
    {
        $excuses = $repo->findBy(["http_code" => $http_code]);
        if ($excuses) {
            return $this->render('excuse/index.html.twig', [
                "excuses" => $excuses
            ]);
        } else {
            return $this->render('bundles/TwigBundle/Exception/error404.html.twig', [
                "excuses" => $excuses
            ]);
        }
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="css/index.css">
    {% endblock %}
</head>

<body>
    {% block header %}{% include "layout/navBar.html.twig" %}{% endblock %}
    <div id="listExcuses">
        {% block body %}
        {% block titre %}<h1 style="text-align:center">Dev Excuses</h1>{% endblock titre %}
        {% if excuses is defined %}
        {% for excuse in excuses %}
        <div class="message">
            <p>{{ excuse.httpCode }}: {{ excuse.message }}</p>
        </div>
        {% block button %}{% endblock %}
        {% endfor %}
        {% endif %}
    </div>
    <button onclick="displayModal()" id="openOrClose" data-open="0">Add Excuse</button>
    <div id="myModal" style="display: none">
        <div>
            <iframe height="250px" width="15%" src="http://localhost:8000/add" frameborder="0"></iframe>
        </div>
    </div>

    {% block javascripts %}
    <script src="{{ asset('js/modal.js') }}"></script>
    {% endblock %}

    {% endblock %}
</body>

</html>

templates/bundles/TwigBundle/Exception/error404.html.twig
<style>
    * {
        background-color: black;
        text-align: center;
    }

    h1 {
        color: gray;
        margin: 20% auto;
        font-size: 50px;
    }
</style>
<h1>ERROR 404</h1>

templates/button/button.html.twig
<form action="/random" method="get">
    <button type="submit">Another Excuse !</button>
</form>

templates/excuse/index.html.twig
{% extends "base.html.twig" %}
{% block button %}
{% include "button/button.html.twig" %}
{% endblock %}

templates/excuseForm/index.html.twig
<style>
    body {
        border: 1px solid black;
        padding: 5%;
    }
</style>

{% block body %}
<h3>Add an Excuse</h3>

{{ form_start(form) }}
{{ form_row(form.http_code) }}
{{ form_row(form.message) }}
{% if error is defined %}
<p>{{ error }}</p>
{% endif %}
<p>Try to Escape me !</p>
<button type="submit" class="btn">Validate</button>
{{ form_end(form) }}

{% endblock %}

templates/layout/navBar.html.twig
<style>
    header {
        border: solid 1px black;
        padding: 1%;
        margin: 0 40%;
    }

    a {
        text-decoration: none;
        color: rgb(63, 2, 2);
        font-weight: bold;
        margin: 1%;
    }
</style>

<header>
    <a href="/">Excuses List</a>
    <a href="/random">Random Excuse</a>
</header>

templates/lost/lost.html.twig
<style>
    * {
        text-align: center;
    }
</style>

<body>
    <img src="image/lost.gif" alt="gif lost">

    <script>
        setTimeout(() => {
            document.location.href = "http://localhost:8000/";
        }, 5000);
    </script>
</body>

templates/modal/modal.html.twig
<form action="/add" method="post">
    <input type="text" name="message" placeholder="excuse message">
    <input type="text" name="http_code" placeholder="http_code">
    <button type="submit">Validate</button>
    {% if message is defined %}
    <p>{{ message }}</p>
    {% endif %}
</form>